import { CourseItem } from "../types/catalogue.types";


export const COURSES_DATA: CourseItem[] = [
    {
        id: 1,
        title: "Mathématiques Tle C & D : Maîtrise des Fonctions & Intégrales",
        instructor: "M. Yao Konan (Lycée Classique d'Abidjan)",
        category: "Mathématiques",
        level: "lycee",
        levelBadge: "Terminale C & D",
        duration: "42h de cours",
        promoTag: "-30% BAC",
        rating: 4.9,
        reviewsCount: 890,
        studentsCount: "1 450 élèves",
        price: 14000,
        priceFormatted: "14 000 FCFA",
        originalPriceFormatted: "20 000 FCFA",
        badgeDotColor: "bg-emerald-600",
        categoryColor: "text-emerald-700 dark:text-emerald-400",
        feature: "Wave / MoMo",
        featureIcon: "zap",
        actionText: "S'inscrire",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBrrQ5Z4E5DX5DnY8OQzi7uHxJ8OhPUc5iNkHk37hm3ii4Pz6Gp64UvUip4Z0dhNcW6KJVF4Bv6-dOUIDiV9Q9Wn-FI7BK1zYOvYaF7MfL6KVxwl99BbRTYEBH1q9_zRfVZxqndrjrlb9OnBowYu60MHaDW8ijtkv8gogfS4QNbIKMs9W-t7ZEkMYSgurYWqetRJU8QhPgEb_jmRKxQaC3YcKNU8-ykZLYL7WizvL2lJpGjOXuxv2Yu",
    },
    {
        id: 2,
        title: "Prépa Concours ENA 2025 : Droit Administratif & Culture Générale",
        instructor: "Dr. Kouamé N'Guessan (Ex-Juriste d'État)",
        category: "Droit Public & CG",
        level: "concours",
        levelBadge: "Concours Directs CI",
        duration: "58h de préparation",
        promoTag: "★ Bestseller ENA",
        rating: 4.9,
        reviewsCount: 1420,
        studentsCount: "2 890 candidats",
        price: 25000,
        priceFormatted: "25 000 FCFA",
        originalPriceFormatted: "40 000 FCFA",
        badgeDotColor: "bg-amber-600",
        categoryColor: "text-amber-700 dark:text-amber-400",
        feature: "Accès 1 an",
        featureIcon: "offline",
        actionText: "Rejoindre la prépa",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDjviDi76RRjtYeCkWnAQxfNTwsjFJb2fj805JoupxplPI9MYljepQTPDwJKMl49OwI_8aLRHnpeenGYpZPGq-ZvapFWS2JMbCYdSzp_sxDVR_UpU3cUUyo0cB3HXWluwo4briFwSiffPghnLtXH457AkDDdzUV0zO1B41c5yxT_9jUMujrO2dKfJIE1Uj9TftyCYYiC6wqlkITFQsU0GNjUzM7tOpmzYrF2eRyS9ZO407axP-nU86h",
    },
    {
        id: 3,
        title: "Développeur Web Fullstack Moderne : Python, Django & Tailwind CSS",
        instructor: "Amina Bakayoko (Lead Dev Abidjan)",
        category: "Développement Web",
        level: "pro",
        levelBadge: "Bootcamp Métier",
        duration: "65h de tutoriels",
        promoTag: "Projet Pro",
        rating: 4.85,
        reviewsCount: 2110,
        studentsCount: "3 400 apprenants",
        price: 35000,
        priceFormatted: "35 000 FCFA",
        originalPriceFormatted: "50 000 FCFA",
        badgeDotColor: "bg-teal-600",
        categoryColor: "text-teal-700 dark:text-teal-400",
        feature: "Certifiant",
        featureIcon: "cert",
        actionText: "Commencer le code",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDYCPNLH8a014VPpBxUqGvlPhx-uocZoGZA7qH1cAvoSiMGa1qWjkQIUNElzHWH_UkV-MOB__L_05wjweIIUUvhIEIt1XuBm5dPL6Nhi4EiGUI7UhCtHpCXJXwAAc_58H8oKFYc_lt6kEFnfP3pgYRcHHTEmZJvbztRp5bCR5wwsfhaTgmbk5YwHTa7BvMlklQ8xhSmdI9xP6fsOt-mq2-J-cizJQQ2pY_Fx0q9EmcPIxH50seqEVgU",
    },
    {
        id: 4,
        title: "Comptabilité Générale et Système Comptable OHADA Révisé",
        instructor: "Alain K. Touré (Expert-Comptable agréé)",
        category: "Gestion & OHADA",
        level: "universite",
        levelBadge: "Entreprise & Finance",
        duration: "32h pratiques",
        rating: 4.8,
        reviewsCount: 670,
        studentsCount: "910 inscrits",
        price: 18000,
        priceFormatted: "18 000 FCFA",
        badgeDotColor: "bg-emerald-600",
        categoryColor: "text-emerald-700 dark:text-emerald-400",
        feature: "Modèles Excel inclus",
        featureIcon: "excel",
        actionText: "Acheter la formation",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1zxqmHHmEfPESwNKvcgPNumyHirwkwvhXaqKZOu-wbjql3Vq0M6SKs5naZRZo4UAJVzTP0x60Hjr5VpuL_9g7pnzg-yKq_L-fSiTPhJ4XlpbqMLcG_FXfJ00kVynNGB1UdG3tIQ5lNLd_e-Wu3aNA3LiL2e8fnLfAz_bW7OiDwjSqf2eLlc8iNrvhFmb1S0rkx98DjhI_ehhNMwEFoLwq0ZiQV5klzZDLwrUYkXG8-uNj_fbZFIv_",
    },
    {
        id: 5,
        title: "Physique-Chimie 1ère C & D : Mécanique & Solutions Aqueuses",
        instructor: "Mme Viviane Koffi (Professeur Principal)",
        category: "Sciences Physiques",
        level: "lycee",
        levelBadge: "Lycée 1ère",
        duration: "28h de leçons",
        rating: 4.7,
        reviewsCount: 520,
        studentsCount: "830 inscrits",
        price: 12000,
        priceFormatted: "12 000 FCFA",
        badgeDotColor: "bg-teal-600",
        categoryColor: "text-teal-700 dark:text-teal-400",
        feature: "Téléchargeable",
        featureIcon: "download",
        actionText: "S'inscrire au cours",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAEu14Y2U93F754FuEP4_CGRdjaySpeUdWxLXOyuoB-iajfvqTgGEOT1w60lYsVsn36eLqCx45kMEb2AEb03zUA0wI_iYZDQXu-JZTfv-6HqXd5kcMirDWjBUe5nH1EpnCmpTPY3xNvB_oSSGtZQgJzzaJ6gmxOhpc36aWudq_QrHD1741DEPFgbDryGvdLOr6F2mSs-wFQdKH2k7E-imXS71xmq-FEz1-5QXEo86MPWB41xJ46NwcZ",
    },
    {
        id: 6,
        title: "Anglais Professionnel des Affaires & Préparation TOEFL",
        instructor: "John Mensah (Formateur Bilingue Certifié)",
        category: "Langues & Carrière",
        level: "pro",
        levelBadge: "International & Pro",
        duration: "30h d'écoute & tests",
        promoTag: "-32% Spécial",
        rating: 4.8,
        reviewsCount: 940,
        studentsCount: "1 750 inscrits",
        price: 15000,
        priceFormatted: "15 000 FCFA",
        originalPriceFormatted: "22 000 FCFA",
        badgeDotColor: "bg-amber-600",
        categoryColor: "text-amber-700 dark:text-amber-400",
        feature: "Audio inclus",
        featureIcon: "audio",
        actionText: "Rejoindre la session",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAme2FIc0DLDgw0lQC_OMx3XpWyxA_4yFc_xjwREje6ZnXLIvAD1Y4Ck1mNlkS37mfeI9zOOdwLUIpCAr4cLDlUQgeVYtkTXQ5o8eKN4JK3X5wsQuPd7e4fY4vXvW7qEVgMjod_qNVJiujeKVkfaAKo5QRSDxFNwd3wyy2lgjVsT0Pv7gIDvcUjknkkU9fZ88PK3rzzScTSehj7GXy5IKbpq01_V6BEDP4KyvSvzJK9S1rcyYy4YzHI",
    },
];
